parameters:
    draw.exception_subscriber.violation_key: errors

services:
    draw.exception_subscriber:
        class: Draw\DrawBundle\EventListener\ApiExceptionSubscriber
        arguments:
            - '@draw.error_handling.exception_message_formatter'
            - '%kernel.debug%'
            - '%fos_rest.exception.codes%'
            - '%draw.exception_subscriber.violation_key%'
        calls:
            - [setLogger, ['@logger']]
        tags:
            - { name: kernel.event_subscriber }